---
- hosts: 43.204.221.253
  become: true
  tasks:
  - name: delete the old version node exporter binary
    file:
     path: /usr/local/bin/node_exporter
     state: absent
  - name: download the node exporter tar file
    get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /tmp
  - name: unpack the tar file
    command: chdir=/tmp tar -xf node_exporter-1.3.1.linux-amd64.tar.gz
  - name: Move the node export binary to /usr/local/bin
    command: chdir=/tmp/node_exporter-1.3.1.linux-amd64 mv node_exporter /usr/local/bin/
  - name: Create a node_exporter user to run the node exporter service
    user:
       name: node_exporter
       shell: /bin/false
  - name: Change the permission of service file
    file: 
      path: /etc/systemd/system/node_exporter.service
      mode: '0755'
  - name: Reload the system daemon
    command: systemctl daemon-reload 
  - name: start the node exporter service
    command: systemctl start node_exporter
  - name: Enable the node exporter service to the system startup
    command: systemctl enable node_exporter
